### ISSUE TITLE
"Improve disableforgegenerate configuration" breaks falling block entities

### ISSUE THREAD

**Issue by Agrrox** [Teneted/Tenet#1650]
**Minecraft Version :** 1.12.2
**Mohist Version :** #247
**Operating System :** Ubuntu Server

**Logs :** none
 <details><summary>Mod list :</summary>

```yml
Name : Minecraft
ModID : minecraft
Version : 1.12.2
---------
Name : Minecraft Coder Pack
ModID : mcp
Version : 9.42
---------
Name : Mohist
ModID : mohist
Version : 1.12.2-247
---------
Name : Forge Mod Loader
ModID : FML
Version : 8.0.99.99
---------
Name : Minecraft Forge
ModID : forge
Version : 14.23.5.2854
---------
Name : Cubic Chunks Coremod
ModID : cubicchunkscore
Version : 1.12.2-0.0.1199.0-SNAPSHOT
---------
Name : Aroma1997Core
ModID : aroma1997core
Version : 2.0.0.2.b167
---------
Name : AromaBackup
ModID : aromabackup
Version : 3.0.0.0.b135
---------
Name : AromaBackuprecovery
ModID : aromabackuprecovery
Version : 3.0.0.0.b135
---------
Name : Banner mod
ModID : bannermod
Version : 1.1.0
---------
Name : Cubic Chunks Pregenerator
ModID : ccpregen
Version : 0.0.21
---------
Name : CubicChunks
ModID : cubicchunks
Version : 1.12.2-0.0.1199.0-SNAPSHOT
---------
Name : CubicGen
ModID : cubicgen
Version : 1.12.2-0.0.151.0-SNAPSHOT
---------
Name : JourneyMap
ModID : journeymap
Version : 1.12.2-5.7.1
---------
Name : RealCoords
ModID : realcoords
Version : 0.0.6
---------
Name : TerraPlusPlus
ModID : terraplusplus
Version : 1.1.0.604-1.12.2
---------
Name : Terra++: Improved Common Datasets Add-on
ModID : terracommondatasets
Version : 0.2
---------
Name : Terra++: Custom Tree Repo Add-on
ModID : terracustomtreerepo
Version : 0.2.4
---------
Name : Terra++: Improved Biomes Add-on
ModID : terraimprovedbiomes
Version : 0.2.1
---------
Name : Terramap
ModID : terramap
Version : 1.0.0-beta7.9_1.12.2
---------
```

</details>

 <details><summary>Mod list :</summary>

```yml
Name : CoreProtect
Version : 2.14.4
---------
Name : LuckPerms
Version : 5.3.47
---------
Name : WorldEdit
Version : 6.1.11-SNAPSHOT-BukkitCcCompat1;9629fff
---------
Name : Sledgehammer
Version : 0.4.2
---------
Name : BannerText
Version : 1.12.2-1
---------
Name : PlaceholderAPI
Version : 2.10.9
---------
Name : TabTPS
Version : 1.3.8
---------
Name : WorldGuard
Version : 6.2.2-SNAPSHOT;8eeab68
---------
Name : ProtocolLib
Version : 4.5.1
---------
Name : DebugStick
Version : 1.1
---------
Name : SchematicBrush
Version : 0.5.2-20
---------
Name : BungeeGuard
Version : 1.0-SNAPSHOT
---------
Name : VoxelSniper
Version : 5.171.0-CC_COMPAT-SNAPSHOT
---------
Name : BetterBrushes
Version : 1.0.0.140406
---------
Name : Vault
Version : 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
---------
Name : RelativeCoordCalculator
Version : 0.5
---------
Name : F3NPerm
Version : 2.5
---------
Name : VentureChat
Version : 2.23.3
---------
Name : Skript
Version : 2.5.3
---------
Name : LastLoginAPI
Version : 1.5.2
---------
Name : Essentials
Version : 2.18.2.0
---------
Name : BKCommonLib
Version : 1.17.1-v1-SNAPSHOT
---------
Name : AnnouncerPlus
Version : 1.2.5
---------
Name : AdvancedBan
Version : 2.3.0
---------
Name : LightCleaner
Version : 1.16.5-v1
---------
Name : ExtraContexts
Version : 2.0-SNAPSHOT
---------
Name : HeadDatabase
Version : 4.14.1
---------
Name : HolographicDisplays
Version : 2.4.9
---------
Name : CommandSigns
Version : 1.6.7
---------
Name : BannerMaker
Version : 1.9.0
---------
Name : DiscordSRV
Version : 1.23.0
---------
Name : SkBee
Version : 1.10.2
---------
Name : DeluxeMenus
Version : 1.13.3-Release
---------
Name : ItemJoin
Version : 5.2.2-RELEASE-b734
---------
Name : EssentialsSpawn
Version : 2.18.2.0
---------
Name : WorldGuardExtraFlags
Version : 4.1.4
---------
Name : BTEIntegration
Version : 1.2
---------
Name : HolographicExtension
Version : 1.10.9
---------
Name : TouchscreenHolograms
Version : 1.4.3
---------
Name : SkQuery
Version : 4.1.5
---------
Name : TuSKe
Version : 1.8.2-Pikachu-Patch-3
---------
```

</details>

**Description of issue :**
the update `#247`(https://github.com/MohistMC/Mohist/commit/59ecb1331e994bf38bd3fffe42fe555dfea8a8db), removed `entities.yml` which had `skip-activation-range`. Not being able to use this breaks the server.
This commit breaks falling blocks due to them being far outside of the center of the world.
![glitched_falling_blocks](https://user-images.githubusercontent.com/10901821/128638851-703f9754-d336-4b8e-8d89-42f6ea6fc2f6.png)
