### ISSUE TITLE
[1.16.5]black mod list option not work properly

### ISSUE THREAD

**Issue by Tollainmear** [Teneted/Tenet#2196]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-997

**Operating System :** windows server 2022

**Logs :** none

**Mod list :** 
• minecraft mohist-1.16.5-997-server.jar : minecraft (1.16.5) - 1
• maven_libs mohist-1.16.5-997-universal.jar : forge (36.2.35) - 1

**Plugin list :** none

**Description of issue :** 
The option of `modsblacklist`(which is in the mohist.yml) may not work properly, when the `list` parameter accept a list, the element in the list can't be matched by single, which I mean, if I set the parameter like this:
```
forge:
  modsblacklist:
    enable: true
    list: xray,autoattack
    kickmessage: Use of unauthorized mods
```
or
```
forge:
  modsblacklist:
    enable: true
    list: 
      - xray
      - autoattact
    kickmessage: Use of unauthorized mods
```
as well as this after reload:
```
forge:
  modsblacklist:
    enable: true
    list: '[xray, autoattact]'
    kickmessage: Use of unauthorized mods
```
When a client with only `xray` but no `autoattack` loaded, it can pass the blacklist check and join the server, but what I expect is that the client with any mod listed by config should be blocked.

And if I set the parameter as below:
```
forge:
  modsblacklist:
    enable: true
    list: xray
    kickmessage: Use of unauthorized mods
```
It seems work properly that server could block any client with xray mod loaded.

So the problem is, how can I set the blacklist compare method to `contains any in list` but not `equal all`?
