### ISSUE TITLE
[1.20.1] Could not load recruitsTeamData for Team 6TeqTabancaA because Team == null

### ISSUE THREAD

**Issue by TeQTabanca** [Teneted/Tenet#3297]
**Minecraft Version :** 1.20.1

**Mohist Version :** Mohist - 1.20.1-824, Java(22.0.1) 66.0

**Operating System :** Windows

**Concerned mod / plugin** : [recruits-1.20.1-1.11.4](https://www.curseforge.com/minecraft/mc-mods/recruits/download/5619377)

**Logs :** [Logs](https://gist.github.com/TeQTabanca/811dd5db5c06ffe06092a8ceef159a54)

**Steps to Reproduce :**
 1. Download the mod and add it to the server
 2. Start the server
 3. Open the team screen
 4. Click on the "View team" button

**Description of issue :** When I click on the "Team list" button, I cannot join any team.

**Comment by TeQTabanca** [comment]
### Update: 
**This problem appears to be occurring because the scoreboard-teams feature in the [TAB](https://www.spigotmc.org/resources/tab-1-5-1-21-1.57806) plugin is turned on.**

```yml
scoreboard-teams:
  enabled: true (If you set this to false, the problem is solved)
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
  sorting-types:
    - "GROUPS:owner,admin,mod,helper,builder,vip,default"
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
```
