### ISSUE TITLE
[1.20.1]如何使用mohist.yml中的server_modlist_whitelist功能

### ISSUE THREAD

**Issue by jitangman** [Teneted/Tenet#3420]
mohist-1.20.1-896-server.jar 生成的mohist.yml中的内容wiki(https://wiki.mohistmc.com/）中似乎并未完全写完整，我想使用其中的server_modlist_whitelist功能 但我不知道如何去使用（如何书写格式？）,请将wiki上补全或请告诉我如何使用这个功能，谢谢
![5c8c7aab-f00b-4681-bb5d-8cf14aee527c](https://github.com/user-attachments/assets/a3079350-00cf-4463-95e8-a0a3a13a2199)
![8e90322dbbffba07cbcde9e7dcc9f28f](https://github.com/user-attachments/assets/d2505de0-f8c4-4d63-b7a7-5118576cc06d)
第一张图片为mohist.yml截图 第二张图片为wiki（https://wiki.mohistmc.com/）上此文件的的截图

**Comment by ProjectSky** [comment]
就是个列表，按照以下格式填入MODID即可
```yaml
server_modlist_whitelist:
  enable: true
  list: '[mod_id1,mod_id2]'
```
注意，启用后客户端使用任何不在白名单内的MOD都将无法连接
